FROM ros:noetic

ENV TZ=UTC
ENV SIZEW=1920
ENV SIZEH=1080
ENV REFRESH=60
ENV DPI=96
ENV CDEPTH=24
ENV VGL_DISPLAY=egl
ENV PASSWD=mypasswd
ENV NOVNC_ENABLE=false
ENV WEBRTC_ENCODER=nvh264enc
ENV WEBRTC_ENABLE_RESIZE=false
ENV ENABLE_AUDIO=true
ENV ENABLE_BASIC_AUTH=true

ARG NOVNC_VERSION=1.3.0

RUN apt-get clean && \
    apt-get update && apt-get install --no-install-recommends -y locales &&\
    rm -rf /var/lib/apt/lists/* && \
    locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update

RUN apt-get install --no-install-recommends -y \
        software-properties-common \
        alsa-base \
        alsa-utils \
        apt-transport-https \
        apt-utils \
        build-essential \
        ca-certificates \
        cups-filters \
        cups-common \
        cups-pdf \
        curl \
        file \
        wget \
        xz-utils \
        zstd \
        gcc \
        git \
        jq \
        python3 \
        supervisor \
        net-tools \
        xserver-xorg-input-all \
        xserver-xorg-video-all \
        xdg-utils \
        dbus-x11 \
        libdbus-c++-1-0v5 \
        xkb-data \
        x11-xkb-utils \
        x11-xserver-utils \
        x11-utils \
        x11-apps \
        xauth \
        xbitmaps \
        xinit \
        xfonts-base \
        libxrandr-dev \
        xvfb

ENV XDG_CURRENT_DESKTOP=KDE
ENV KWIN_COMPOSE=N
ENV SUDO_EDITOR=kate
ENV PULSE_SERVER=unix:/run/pulse/native

RUN apt-get update && apt-get install --no-install-recommends -y \
        kde-plasma-desktop \
        terminator \
        kinfocenter \
        kwin-x11 \
        plasma-desktop \
        plasma-nm \
        plasma-widgets-addons \
        plasma-workspace \
        autoconf \
        automake \
        autotools-dev \
        chrpath \
        debhelper \
        git \
        python3 \
        python3-pip \
        python-is-python3 \
        libc6-dev \
        libcairo2-dev \
        libjpeg-turbo8-dev \
        libssl-dev \
        libv4l-dev \
        libvncserver-dev \
        libtool-bin \
        libxdamage-dev \
        libxinerama-dev \
        libxrandr-dev \
        libxss-dev \
        libxtst-dev \
        libavahi-client-dev && \
    rm -rf /var/lib/apt/lists/*  && \
    git clone "https://github.com/LibVNC/x11vnc.git" /tmp/x11vnc && \
    cd /tmp/x11vnc && autoreconf -fi && ./configure && make install && cd / && rm -rf /tmp/* && \
    curl -fsSL "https://github.com/novnc/noVNC/archive/v${NOVNC_VERSION}.tar.gz" | tar -xzf - -C /opt && \
    mv -f "/opt/noVNC-${NOVNC_VERSION}" /opt/noVNC && \
    ln -snf /opt/noVNC/vnc.html /opt/noVNC/index.html && \
    git clone "https://github.com/novnc/websockify.git" /opt/noVNC/utils/websockify

RUN apt update && apt install -y rviz \
         ros-noetic-moveit \
         curl \
         apt-utils \
         python3-pip \
         python-is-python3 \
         net-tools \
         nmap \
         xauth \
         ros-noetic-robot-state-publisher \
         ros-noetic-joint-state-publisher \
         git \
         ros-noetic-usb-cam \
         htop \
         libxmlrpc-core-c3-dev

RUN pip install catkin_tools \
                tensorboard

RUN apt-get update && apt-get install --no-install-recommends -y \
                sudo && \
            rm -rf /var/lib/apt/lists/* && \
            groupadd -g 1000 laboratorio && \
            useradd -ms /bin/bash laboratorio -u 1000 -g 1000 && \
            usermod -a -G adm,audio,cdrom,dialout,dip,fax,floppy,input,lp,lpadmin,plugdev,sudo,tape,tty,video,voice laboratorio && \
            echo "laboratorio ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
            chown laboratorio:laboratorio /home/laboratorio && \
            mkdir -p /var/run/laboratorio/1000 && \
            chown laboratorio:laboratorio /var/run/laboratorio/1000 && \
            echo "laboratorio:laboratorio" | chpasswd && \
            ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone

RUN pip install ur_rtde

COPY entrypoint.sh /etc/entrypoint.sh
RUN chmod 755 /etc/entrypoint.sh
COPY supervisord.conf /etc/supervisord.conf
RUN chmod 755 /etc/supervisord.conf

RUN echo "source /opt/ros/noetic/setup.bash" >> /home/laboratorio/.bashrc

USER laboratorio
ENV SHELL /bin/bash
ENV USER=laboratorio
ENV DISPLAY=:0

ENTRYPOINT ["/usr/bin/supervisord"]